// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v4.23.4
// source: protocol/messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_DA_RESPONSE           MessageType = 0
	MessageType_HEARTBEAT             MessageType = 1
	MessageType_VOTE_REQUEST_RECEIVED MessageType = 2
	MessageType_VOTE_RECEIVED         MessageType = 3
	MessageType_LOG_ENTRY_REPLICATED  MessageType = 4
	MessageType_LOG_ENTRY_COMMITTED   MessageType = 5
	MessageType_LEADER_SUSPECTED      MessageType = 6
	MessageType_FOLLOWER_SUSPECTED    MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "DA_RESPONSE",
		1: "HEARTBEAT",
		2: "VOTE_REQUEST_RECEIVED",
		3: "VOTE_RECEIVED",
		4: "LOG_ENTRY_REPLICATED",
		5: "LOG_ENTRY_COMMITTED",
		6: "LEADER_SUSPECTED",
		7: "FOLLOWER_SUSPECTED",
	}
	MessageType_value = map[string]int32{
		"DA_RESPONSE":           0,
		"HEARTBEAT":             1,
		"VOTE_REQUEST_RECEIVED": 2,
		"VOTE_RECEIVED":         3,
		"LOG_ENTRY_REPLICATED":  4,
		"LOG_ENTRY_COMMITTED":   5,
		"LEADER_SUSPECTED":      6,
		"FOLLOWER_SUSPECTED":    7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_protocol_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_NOOP_ACTION_TYPE                ActionType = 0
	ActionType_HALT_ACTION_TYPE                ActionType = 1
	ActionType_PAUSE_ACTION_TYPE               ActionType = 2
	ActionType_STOP_ACTION_TYPE                ActionType = 3
	ActionType_RESEND_LAST_MESSAGE_ACTION_TYPE ActionType = 4
	ActionType_CONTINUE_ACTION_TYPE            ActionType = 5
	ActionType_RESTART_ACTION_TYPE             ActionType = 6
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "NOOP_ACTION_TYPE",
		1: "HALT_ACTION_TYPE",
		2: "PAUSE_ACTION_TYPE",
		3: "STOP_ACTION_TYPE",
		4: "RESEND_LAST_MESSAGE_ACTION_TYPE",
		5: "CONTINUE_ACTION_TYPE",
		6: "RESTART_ACTION_TYPE",
	}
	ActionType_value = map[string]int32{
		"NOOP_ACTION_TYPE":                0,
		"HALT_ACTION_TYPE":                1,
		"PAUSE_ACTION_TYPE":               2,
		"STOP_ACTION_TYPE":                3,
		"RESEND_LAST_MESSAGE_ACTION_TYPE": 4,
		"CONTINUE_ACTION_TYPE":            5,
		"RESTART_ACTION_TYPE":             6,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_messages_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_protocol_messages_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType   MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	ActionType    ActionType  `protobuf:"varint,2,opt,name=actionType,proto3,enum=ActionType" json:"actionType,omitempty"`
	LogMessage    string      `protobuf:"bytes,3,opt,name=logMessage,proto3" json:"logMessage,omitempty"`
	MessageObject *anypb.Any  `protobuf:"bytes,4,opt,name=messageObject,proto3" json:"messageObject,omitempty"`
	CustomData    *CustomData `protobuf:"bytes,5,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_DA_RESPONSE
}

func (x *Message) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_NOOP_ACTION_TYPE
}

func (x *Message) GetLogMessage() string {
	if x != nil {
		return x.LogMessage
	}
	return ""
}

func (x *Message) GetMessageObject() *anypb.Any {
	if x != nil {
		return x.MessageObject
	}
	return nil
}

func (x *Message) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type DAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseType string `protobuf:"bytes,1,opt,name=responseType,proto3" json:"responseType,omitempty"`
}

func (x *DAResponse) Reset() {
	*x = DAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAResponse) ProtoMessage() {}

func (x *DAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAResponse.ProtoReflect.Descriptor instead.
func (*DAResponse) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DAResponse) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

type CustomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolName string     `protobuf:"bytes,1,opt,name=protocolName,proto3" json:"protocolName,omitempty"`
	Data         *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CustomData) Reset() {
	*x = CustomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomData) ProtoMessage() {}

func (x *CustomData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomData.ProtoReflect.Descriptor instead.
func (*CustomData) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CustomData) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *CustomData) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type VoteRequestReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestingNodeId uint32 `protobuf:"varint,1,opt,name=requestingNodeId,proto3" json:"requestingNodeId,omitempty"`
	ReceivingNodeId  uint32 `protobuf:"varint,2,opt,name=receivingNodeId,proto3" json:"receivingNodeId,omitempty"`
}

func (x *VoteRequestReceived) Reset() {
	*x = VoteRequestReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequestReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequestReceived) ProtoMessage() {}

func (x *VoteRequestReceived) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequestReceived.ProtoReflect.Descriptor instead.
func (*VoteRequestReceived) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{3}
}

func (x *VoteRequestReceived) GetRequestingNodeId() uint32 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

func (x *VoteRequestReceived) GetReceivingNodeId() uint32 {
	if x != nil {
		return x.ReceivingNodeId
	}
	return 0
}

type VoteReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VotingNodeId uint32 `protobuf:"varint,1,opt,name=votingNodeId,proto3" json:"votingNodeId,omitempty"`
	VotedNodeId  uint32 `protobuf:"varint,2,opt,name=votedNodeId,proto3" json:"votedNodeId,omitempty"`
	VoteGranted  bool   `protobuf:"varint,3,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
}

func (x *VoteReceived) Reset() {
	*x = VoteReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReceived) ProtoMessage() {}

func (x *VoteReceived) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReceived.ProtoReflect.Descriptor instead.
func (*VoteReceived) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{4}
}

func (x *VoteReceived) GetVotingNodeId() uint32 {
	if x != nil {
		return x.VotingNodeId
	}
	return 0
}

func (x *VoteReceived) GetVotedNodeId() uint32 {
	if x != nil {
		return x.VotedNodeId
	}
	return 0
}

func (x *VoteReceived) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type LogEntryReplicated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId        uint32 `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	ReceivingNodeId uint32 `protobuf:"varint,2,opt,name=receivingNodeId,proto3" json:"receivingNodeId,omitempty"`
	LogEntryNumber  int64  `protobuf:"varint,3,opt,name=logEntryNumber,proto3" json:"logEntryNumber,omitempty"`
}

func (x *LogEntryReplicated) Reset() {
	*x = LogEntryReplicated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryReplicated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryReplicated) ProtoMessage() {}

func (x *LogEntryReplicated) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryReplicated.ProtoReflect.Descriptor instead.
func (*LogEntryReplicated) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntryReplicated) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LogEntryReplicated) GetReceivingNodeId() uint32 {
	if x != nil {
		return x.ReceivingNodeId
	}
	return 0
}

func (x *LogEntryReplicated) GetLogEntryNumber() int64 {
	if x != nil {
		return x.LogEntryNumber
	}
	return 0
}

type LogEntryCommitted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId        uint32 `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	ReceivingNodeId uint32 `protobuf:"varint,2,opt,name=receivingNodeId,proto3" json:"receivingNodeId,omitempty"`
	LogEntryNumber  int64  `protobuf:"varint,3,opt,name=logEntryNumber,proto3" json:"logEntryNumber,omitempty"`
}

func (x *LogEntryCommitted) Reset() {
	*x = LogEntryCommitted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryCommitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryCommitted) ProtoMessage() {}

func (x *LogEntryCommitted) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryCommitted.ProtoReflect.Descriptor instead.
func (*LogEntryCommitted) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntryCommitted) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LogEntryCommitted) GetReceivingNodeId() uint32 {
	if x != nil {
		return x.ReceivingNodeId
	}
	return 0
}

func (x *LogEntryCommitted) GetLogEntryNumber() int64 {
	if x != nil {
		return x.LogEntryNumber
	}
	return 0
}

type LeaderSuspected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId         uint32 `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	SuspectingNodeId uint32 `protobuf:"varint,2,opt,name=suspectingNodeId,proto3" json:"suspectingNodeId,omitempty"`
}

func (x *LeaderSuspected) Reset() {
	*x = LeaderSuspected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderSuspected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderSuspected) ProtoMessage() {}

func (x *LeaderSuspected) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderSuspected.ProtoReflect.Descriptor instead.
func (*LeaderSuspected) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderSuspected) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LeaderSuspected) GetSuspectingNodeId() uint32 {
	if x != nil {
		return x.SuspectingNodeId
	}
	return 0
}

type FollowerSuspected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId   uint32 `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	FollowerId uint32 `protobuf:"varint,2,opt,name=followerId,proto3" json:"followerId,omitempty"`
}

func (x *FollowerSuspected) Reset() {
	*x = FollowerSuspected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerSuspected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerSuspected) ProtoMessage() {}

func (x *FollowerSuspected) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerSuspected.ProtoReflect.Descriptor instead.
func (*FollowerSuspected) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{8}
}

func (x *FollowerSuspected) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *FollowerSuspected) GetFollowerId() uint32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

var File_protocol_messages_proto protoreflect.FileDescriptor

var file_protocol_messages_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a,
	0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x0a, 0x44, 0x41,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5a, 0x0a, 0x0a,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x13, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12,
	0x2a, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x0c, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x76, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x6f, 0x74,
	0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x76, 0x6f, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x76,
	0x6f, 0x74, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x76, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x22, 0x82, 0x01,
	0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e,
	0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x10, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x22, 0x4f, 0x0a, 0x11, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x75, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x49, 0x64, 0x2a, 0xbc, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x41, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54,
	0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x56, 0x4f, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x56, 0x4f, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x18, 0x0a, 0x14, 0x4c, 0x4f, 0x47, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x52, 0x45,
	0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x4f,
	0x47, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x54, 0x45,
	0x44, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x55,
	0x53, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f, 0x4c,
	0x4c, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10,
	0x07, 0x2a, 0xbd, 0x01, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x4f, 0x50, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x41, 0x4c, 0x54, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x41, 0x55, 0x53, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x03, 0x12, 0x23, 0x0a, 0x1f, 0x52, 0x45, 0x53,
	0x45, 0x4e, 0x44, 0x5f, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x04, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10,
	0x06, 0x42, 0x12, 0x5a, 0x10, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_messages_proto_rawDescOnce sync.Once
	file_protocol_messages_proto_rawDescData = file_protocol_messages_proto_rawDesc
)

func file_protocol_messages_proto_rawDescGZIP() []byte {
	file_protocol_messages_proto_rawDescOnce.Do(func() {
		file_protocol_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_messages_proto_rawDescData)
	})
	return file_protocol_messages_proto_rawDescData
}

var file_protocol_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protocol_messages_proto_goTypes = []interface{}{
	(MessageType)(0),            // 0: MessageType
	(ActionType)(0),             // 1: ActionType
	(*Message)(nil),             // 2: Message
	(*DAResponse)(nil),          // 3: DAResponse
	(*CustomData)(nil),          // 4: CustomData
	(*VoteRequestReceived)(nil), // 5: VoteRequestReceived
	(*VoteReceived)(nil),        // 6: VoteReceived
	(*LogEntryReplicated)(nil),  // 7: LogEntryReplicated
	(*LogEntryCommitted)(nil),   // 8: LogEntryCommitted
	(*LeaderSuspected)(nil),     // 9: LeaderSuspected
	(*FollowerSuspected)(nil),   // 10: FollowerSuspected
	(*anypb.Any)(nil),           // 11: google.protobuf.Any
}
var file_protocol_messages_proto_depIdxs = []int32{
	0,  // 0: Message.messageType:type_name -> MessageType
	1,  // 1: Message.actionType:type_name -> ActionType
	11, // 2: Message.messageObject:type_name -> google.protobuf.Any
	4,  // 3: Message.customData:type_name -> CustomData
	11, // 4: CustomData.data:type_name -> google.protobuf.Any
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_messages_proto_init() }
func file_protocol_messages_proto_init() {
	if File_protocol_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequestReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryReplicated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryCommitted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderSuspected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerSuspected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_messages_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_messages_proto_goTypes,
		DependencyIndexes: file_protocol_messages_proto_depIdxs,
		EnumInfos:         file_protocol_messages_proto_enumTypes,
		MessageInfos:      file_protocol_messages_proto_msgTypes,
	}.Build()
	File_protocol_messages_proto = out.File
	file_protocol_messages_proto_rawDesc = nil
	file_protocol_messages_proto_goTypes = nil
	file_protocol_messages_proto_depIdxs = nil
}
