ARG ARCH=amd64
FROM --platform=linux/${ARCH} ubuntu:22.10

ADD config /thesis/config
ADD bin/da /thesis/da
ADD deploy/da-run.sh /thesis/da-run.sh

RUN apt update && apt -qy full-upgrade && apt install -qy gettext-base bash curl && curl -fsSL https://get.docker.com/ | sh

WORKDIR /thesis

EXPOSE 8080

ENTRYPOINT ["bash", "da-run.sh"]