ARG ARCH=amd64
#FROM --platform=linux/${ARCH} gcr.io/distroless/static-debian11
FROM --platform=linux/${ARCH} ubuntu:22.04

ADD config /thesis/config
ADD deploy/etcd-run.sh /thesis/etcd-run.sh

COPY bin/etcd /usr/local/bin/
COPY bin/etcdctl /usr/local/bin/
COPY bin/etcdutl /usr/local/bin/

RUN apt-get update && apt-get -qy full-upgrade && apt-get install -qy gettext-base bash curl

#RUN apt-get update

WORKDIR /var/etcd/
WORKDIR /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
#ARG CLUSTER_STRING
#ENV CLUSTER=${CLUSTER_STRING}
#CMD ["bash", "-c", "/usr/local/bin/etcd --initial-advertise-peer-urls http://${ETCD_IP}:${ETCD_GRPC_PORT} --listen-peer-urls http://${ETCD_IP}:${ETCD_GRPC_PORT} --advertise-client-urls http://${ETCD_IP}:${ETCD_CLIENT_PORT} --listen-client-urls http://${ETCD_IP}:${ETCD_CLIENT_PORT} --initial-cluster ${CLUSTER}"]
ENTRYPOINT ["bash", "/thesis/etcd-run.sh"]