networks:
  consensus:

services:
  bftsmart:
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    image: "${BFTSMART_IMAGE_NAME}:${BFTSMART_IMAGE_VERSION}"
#    networks:
#      - consensus
    ports:
      - 11000:11000
      - 11001:11001
    volumes:
      - "${DA_VOLUME_PATH}:${DA_CONTAINER_VOLUME_PATH}"
    environment:
      - INSTANCE_NUMBER=${INSTANCE_NUMBER}
    env_file:
      - "./.env-cluster"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  etcd:
    cap_add:
      - NET_ADMIN
    image: "${ETCD_IMAGE_NAME}:${ETCD_IMAGE_VERSION}"
    networks:
      - consensus
    ports:
      - "${EXTERNAL_CLIENT_PORT}:${ETCD_CLIENT_CONTAINER_PORT}"
      - "${EXTERNAL_GRPC_PORT}:${ETCD_GRPC_CONTAINER_PORT}"
    volumes:
      - "${DA_VOLUME_PATH}:${DA_CONTAINER_VOLUME_PATH}"
    environment:
      - ETCD_NAME=${ETCD_INSTANCE_NAME}
      - ETCD_CLIENT_PORT=${ETCD_CLIENT_PORT}
      - ETCD_GRPC_PORT=${ETCD_GRPC_PORT}
      - ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER}
      - ETCD_LISTEN_CLIENT_URLS=http://${ETCD_LISTEN_IP}:${ETCD_CLIENT_CONTAINER_PORT}
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:${EXTERNAL_CLIENT_PORT}
      - ETCD_LISTEN_PEER_URLS=http://${ETCD_LISTEN_IP}:${ETCD_GRPC_CONTAINER_PORT}
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${HOST_IP}:${EXTERNAL_GRPC_PORT}
      - ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_CLUSTER_TOKEN}
      - ETCD_INITIAL_CLUSTER_STATE=${ETCD_CLUSTER_STATE}
      - INSTANCE_NUMBER=${INSTANCE_NUMBER}
    env_file:
      - "./.env-cluster"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  da:
    cap_add:
      - NET_ADMIN
    image: "${DA_IMAGE_NAME}:${DA_IMAGE_VERSION}"
    networks:
      - consensus
    volumes:
      - "${DA_VOLUME_PATH}:${DA_CONTAINER_VOLUME_PATH}"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CONSENSUS_CONTAINER=${CONSENSUS_CONTAINER_NAME}
      - INSTANCE_NUMBER=${INSTANCE_NUMBER}
    env_file:
      - "./.env-cluster"
    extra_hosts:
      - "host.docker.internal:host-gateway"