networks:
  consensus:

services:
  etcd:
    image: "${ETCD_IMAGE_NAME}:${ETCD_IMAGE_VERSION}"
    networks:
      - consensus
    ports:
      - "${EXTERNAL_CLIENT_PORT}:${ETCD_CLIENT_CONTAINER_PORT}"
      - "${EXTERNAL_GRPC_PORT}:${ETCD_GRPC_CONTAINER_PORT}"
    environment:
      - ETCD_NAME=${ETCD_INSTANCE_NAME}
      - ETCD_CLIENT_PORT=${ETCD_CLIENT_PORT}
      - ETCD_GRPC_PORT=${ETCD_GRPC_PORT}
      - ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER}
      - ETCD_LISTEN_CLIENT_URLS=http://${ETCD_LISTEN_IP}:${ETCD_CLIENT_CONTAINER_PORT}
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:${EXTERNAL_CLIENT_PORT}
      - ETCD_LISTEN_PEER_URLS=http://${ETCD_LISTEN_IP}:${ETCD_GRPC_CONTAINER_PORT}
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${HOST_IP}:${EXTERNAL_GRPC_PORT}
      - ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_CLUSTER_TOKEN}
      - ETCD_INITIAL_CLUSTER_STATE=${ETCD_CLUSTER_STATE}
    env_file:
      - "./.env-cluster"
    extra_hosts:
      - "host.docker.internal:host-gateway"

